[package]
name = "e01_basic_ping_bot"
version = "0.1.0"
authors = ["my name <my@email.address>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
serenity = "0.12.4"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
