[package]
name = "discord_gameserver_rc"
version = "0.1.0"
authors = ["Mixteprix realmixteprix@proton.me"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
serenity = "0.12.4"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
